version: 0.2

phases:
  install:
    runtime-versions:
       python: 3.8
    commands:
      - pip install cfn-lint aws-sam-cli
      - echo ${STAGE}
  build:
    commands:
      - cfn-lint -t template.yaml
      - sam validate
artifacts:
  files:
    - packaged-template.yaml