version: 0.2

phases:
  install:
    runtime-versions:
       python: 3.8
    commands:
      - pip install cfn-lint aws-sam-cli -q
      - echo ${STAGE}
  pre_build:
    commands:
      - echo Fase previa
  build:
    commands:
      - cfn-lint -t template.yaml
      - sam build
      - sam deploy --config-env ${STAGE} --no-confirm-changeset --no-fail-on-empty-changeset
artifacts:
  files:
    - packaged-template.yaml