version = 0.1

[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "hello-fastapi-lambda"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1grgpdxgovdy"
s3_prefix = "hello-fastapi-lambda"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = "Stage=\"dev\" TableNamePrefix=\"users\""

[prod]
[prod.deploy]
[prod.deploy.parameters]
stack_name = "sam-codebuild-prod"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1grgpdxgovdy"
s3_prefix = "sam-codebuild-prod"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"prod\""
image_repositories = ["HelloSamDockerFunction=230832512561.dkr.ecr.us-east-1.amazonaws.com/samdockere9ade4b1/hellosamdockerfunctione409fd1erepo"]

[staging]
[staging.deploy]
[staging.deploy.parameters]
stack_name = "fastapi-dynamodb-2"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1grgpdxgovdy"
s3_prefix = "fastapi-dynamodb-2"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"staging\" TableNamePrefix=\"fastapi-users\""
image_repositories = []
